### ISSUE TITLE
bug , documentation  : cors 오류 및 aceess token 설정 및 일정공유

### ISSUE THREAD

**Issue by jiji-hoon96** [h-dt/WeCo_Front#10]
1. 8/25 회의때 cors 오류 진행중입니다
2. 백앤드 코드를 수정한 결과 이유는 모르겠지만 해결이 된거같습니다
3. @dongmin3891  님께서 금일 새벽까지 작업해주시면
4. @hyejinlim  @jiji-hoon96  pr 확인 후에 오류 해결 후 api 분담해 작업하면 될거같습니다
5. 현재 논의된 부분은 social login 의 access token 을 session 에 저장후 각 기능 작업 후 마무리로 자체홈페이지 회원관리를 하자는 의견이 나왔습니다  @hyejinlim  확인후 comment 남겨주시면 감사하겠습니다
6. **8/26 저녁 10시**에 @hyejinlim @dongmin3891 @jiji-hoon96  모여서 회의 후 역할분담을 하면 좋을거같습니다 comment 남겨주세요!

**Comment by myalim** [comment]
오늘은 자정 이후에 시간이 날 것 같습니다. 괜찮으시다면 토요일 오전은 어떠신가요?

**Comment by jiji-hoon96** [comment]
> 오늘은 자정 이후에 시간이 날 것 같습니다. 괜찮으시다면 토요일 오전은 어떠신가요?

저는 좋습니다  토요일 오전 10시쯤 괜찮으실까요?
@hyejinlim  @dongmin3891

**Comment by myalim** [comment]
> > 오늘은 자정 이후에 시간이 날 것 같습니다. 괜찮으시다면 토요일 오전은 어떠신가요?
> 
> 저는 좋습니다 토요일 오전 10시쯤 괜찮으실까요? @hyejinlim @dongmin3891

네 가능합니다. 저는 주말 다 가능하니 편하신 시간 공유해주세요!

**Comment by dongmin3891** [comment]
네네 토요일 10시 괜찮습니다

**Comment by jiji-hoon96** [comment]
> 네네 토요일 10시 괜찮습니다

@hyejinlim @dongmin3891  토요일 10시에 뵐게요!
